language: python

python:
  - "2.7"

before_script:
  - psql -c 'create database openbudgets;' -U postgres

before_install:
  - export CI=true

install:
  - pip install -r requirements.txt

script: coverage run --source='.' manage.py test openbudgets.api openbudgets.apps.accounts openbudgets.apps.contexts openbudgets.apps.entities openbudgets.apps.interactions openbudgets.apps.international openbudgets.apps.pages openbudgets.apps.sheets openbudgets.apps.tools openbudgets.apps.transport

notifications:
  email:
    - paulywalsh@gmail.com
    - maggotfish@gmail.com

on_success: always

on_failure: always

after_success:
  - coverage report
  - pip install --quiet --use-mirrors python-coveralls
  - coveralls
