language: python
python:
  - "2.7"
install: pip install -r requirements/base.txt --use-mirrors
script: python manage.py test accounts api sheets contexts commons entities international pages transport
notifications:
  email:
    - hello@prjts.com
on_success: always
on_failure: always
