local: &LOCAL
  project_name: openbudgets
  project_initial_data:
    - local/sites
  project_allowed_hosts:
  project_cookie_domain:
  project_secret_key:
  project_packages: openbudgets.settings.INSTALLED_APPS
  project_config_file: ./openbudgets/settings/local.py
  project_config_template: fabfile.templates.local
  app_instance: openbudgets.wsgi:application
  queue_instance: openbudgets.queue:app
  repository_location: https://bitbucket.org/pwalsh/openbudgets
  repository_branch: develop
  db_name: openbudgets
  db_dump_file: ./tmp/db_dump.sql
  workon: workon openbudgets
  dock_dataset_location: ./tmp/dataset
  dock_repository_location: https://github.com/prjts/openmuni-israel.git
  dock_repository_branch: master
  dock_prepare_objects: false


staging: &STAGING
  <<: *LOCAL
  roledefs:
    app:
      - 23.236.57.59
    proxy:
      - 23.236.57.59
    cache:
      - 23.236.57.59
    queue:
      - 23.236.57.59
    db:
      - 108.59.81.226
  project_root: /srv/projects/openbudgets
  project_env: /srv/environments/openbudgets
  project_allowed_hosts:
    - staging.openmuni.org.il
  project_cookie_domain: openmuni.org.il
  project_initial_data:
    - staging/sites
  project_config_file: /srv/projects/openbudgets/openbudgets/settings/deploy.py
  project_config_template: fabfile.templates.deploy
  proxy_location: 23.236.57.59
  proxy_port: 80
  proxy_accesslog: /srv/logs/proxy_access.log
  proxy_errorlog: /srv/logs/proxy_error.log
  app_config_file: /srv/projects/openbudgets/config/app.py
  app_accesslog: /srv/logs/app_access.log
  app_errorlog: /srv/logs/app_error.log
  queue_config_file: /srv/projects/openbudgets/config/queue.py
  queue_accesslog: /srv/logs/queue_access.log
  queue_errorlog: /srv/logs/queue_error.log
  cache_accesslog: /srv/logs/cache_access.log
  cache_errorlog: /srv/logs/cache_error.log
  db_location: 10.240.218.108
  db_port: 5432
  db_dump_file: /srv/projects/openbudgets/tmp/db_dump.sql
  dock_dataset_location: /srv/projects/openbudgets/tmp/dataset


master: &MASTER
  <<: *STAGING
  roledefs:
    app:
      - 23.251.149.127
    proxy:
      - 23.251.149.127
    cache:
      - 23.251.149.127
    queue:
      - 23.251.149.127
    db:
      - 108.59.85.161
  project_cookie_domain: openmuni.org.il
  project_initial_data:
    - staging/sites
  db_location: 10.240.51.173
  db_port: 5432
  proxy_location: 23.251.149.127
  proxy_port: 80


ext: &EXT
  <<: *MASTER
  roledefs:
    app:
      - 23.251.149.127
    proxy:
      - 23.251.149.127
    cache:
      - 23.251.149.127
    queue:
      - 23.251.149.127
    db:
      - 108.59.85.161
  project_allowed_hosts:
    - ext.openmuni.org.il
  project_cookie_domain: ext.openmuni.org.il
  project_initial_data:
    - ext/sites
  db_location: 10.240.51.173
  db_port: 5432
  proxy_location: 23.251.149.127
  proxy_port: 80
